version: '3.7'

services:
  frontend:
    image: rowdymagic
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    volumes:
      - .:/app
      - /app/node_modules
    
